// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7IW8xBKXZhmz8vKlwtku87dQsTktOaGg',
    appId: '1:916458160199:web:397806d50e63a4f6fcf162',
    messagingSenderId: '916458160199',
    projectId: 'websiteone-dde44',
    authDomain: 'websiteone-dde44.firebaseapp.com',
    storageBucket: 'websiteone-dde44.firebasestorage.app',
    measurementId: 'G-V1L74KZ60D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN9nZynk9kIK2mZyTCvldFjDXb8IiuMGo',
    appId: '1:916458160199:ios:26f250c7cf12ddb7fcf162',
    messagingSenderId: '916458160199',
    projectId: 'websiteone-dde44',
    storageBucket: 'websiteone-dde44.firebasestorage.app',
    iosBundleId: 'com.example.websiteme',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc8ouOHg6tCLOZ_NUdx0-tA3lSO7m12KY',
    appId: '1:916458160199:android:d84f42f83f30e375fcf162',
    messagingSenderId: '916458160199',
    projectId: 'websiteone-dde44',
    storageBucket: 'websiteone-dde44.firebasestorage.app',
  );

}